variables:
  libiioPipelineId: 9
  libad9361iioPipelineId: 10
  libad9166iioPipelineId: 41

trigger:
- main
- master
- staging/*
- 20*

pr:
- main
- master
- 20*

jobs:
- job: LinuxBuilds
  strategy:
    matrix:
      ubuntu_20_04_x86_64:
        imageName: 'ubuntu-20.04'
        OS_TYPE: 'ubuntu_docker'
        OS_VERSION: focal
        artifactName: 'Linux-Ubuntu-20.04'
        PACKAGE_TO_INSTALL: 'build/*.deb'
        #uncomment these lines when Ubuntu-22.04 is available for libad9361 and libad9166
        #ubuntu_22_04_x86_64:
        #imageName: 'ubuntu-22.04'
        #OS_TYPE: 'ubuntu_docker'
        #OS_VERSION: focal
        #artifactName: 'Linux-Ubuntu-22.04'
        #PACKAGE_TO_INSTALL: 'build/*.deb'
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libiio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libad9361-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9361iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libad9166-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9166iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - script: ./CI/travis/before_install_linux
    displayName: "Install Dependencies"
  - script: ./CI/travis/make_linux
    displayName: "Build"

- job: ARMBuilds
  # Host Box
  pool:
    vmImage: "ubuntu-latest"
  # Docker Images
  strategy:
    matrix:
      ubuntu-ppc64le:
        image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
        arch: ppc64le
        build_script: ci-ubuntu.sh
        artifactName: 'Ubuntu-ppc64le'
      ubuntu-x390x:
        image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
        arch: s390x
        build_script: ci-ubuntu.sh
        artifactName: 'Ubuntu-x390x'
      debian_buster_arm32v7:
        image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
        arch: arm
        build_script: ci-ubuntu.sh
        artifactName: 'Ubuntu-arm32v7'
      debian_buster_arm64v8:
        image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
        arch: aarch64
        build_script: ci-ubuntu.sh
        artifactName: 'Ubuntu-arm64v8'
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libiio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libad9361-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9361iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libad9166-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9166iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'

- job: macOSBuilds
  strategy:
    matrix:
      macOS_11:
        imageName: 'macOS-11'
        artifactName: 'macOS-11'
      macOS_12:
        imageName: 'macOS-12'
        artifactName: 'macOS-12'
  pool:
    vmImage: $(imageName)
  variables:
    PACKAGE_TO_INSTALL: 'build/*.pkg'
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libiio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libad9361-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9361iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    displayName: 'Get libad9166-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9166iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - script: ./CI/travis/before_install_darwin
    displayName: "Install Dependencies"
  - script: ./CI/travis/make_darwin
    displayName: "Build"
